import * as React from 'react';
import { router } from '@inertiajs/react';
import {
    Dialog,
    DialogTrigger,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
    DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Mail, Loader2, Eye } from 'lucide-react';
import { useState } from 'react';
// ContactUsController will be auto-generated by route actions

export default function ViewContactDialog({ 
    contact, 
    trigger 
}: { 
    contact: any;
    trigger?: React.ReactNode;
}) {
    const [open, setOpen] = React.useState(false);
    const [replyMessage, setReplyMessage] = useState('');
    const [sending, setSending] = useState(false);

    const handleReply = () => {
        if (!replyMessage.trim()) {
            alert('Please enter a reply message');
            return;
        }

        setSending(true);
        router.post(
            `/contact-us/${contact.id}/reply`,
            { reply_message: replyMessage },
            {
                onSuccess: () => {
                    setOpen(false);
                    setReplyMessage('');
                },
                onFinish: () => setSending(false),
                preserveScroll: true,
            }
        );
    };

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                {trigger ?? (
                    <Button variant="outline" size="sm">
                        <Eye className="h-4 w-4 mr-2" />
                        View
                    </Button>
                )}
            </DialogTrigger>
            <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle>Inquiry Details</DialogTitle>
                </DialogHeader>
                
                <div className="space-y-4">
                    {/* Contact Information */}
                    <div className="grid gap-3">
                        <div>
                            <Label className="text-xs text-muted-foreground">Source</Label>
                            <p className="text-sm font-medium capitalize">{contact.source || '—'}</p>
                        </div>
                        <div>
                            <Label className="text-xs text-muted-foreground">Name</Label>
                            <p className="text-sm font-medium">{contact.name || '—'}</p>
                        </div>
                        <div>
                            <Label className="text-xs text-muted-foreground">Email</Label>
                            <a
                                className="text-sm block font-medium text-primary hover:underline"
                                href={`mailto:${contact.email}`}
                            >
                                {contact.email}
                            </a>
                        </div>
                        {contact.phone && (
                            <div>
                                <Label className="text-xs text-muted-foreground">Phone</Label>
                                <p className="text-sm font-medium">{contact.phone}</p>
                            </div>
                        )}
                        {contact.subject && (
                            <div>
                                <Label className="text-xs text-muted-foreground">Subject</Label>
                                <p className="text-sm font-medium">{contact.subject}</p>
                            </div>
                        )}
                        {contact.courses && (
                            <div>
                                <Label className="text-xs text-muted-foreground">Related Courses</Label>
                                <p className="text-sm font-medium">{contact.courses}</p>
                            </div>
                        )}
                        <div>
                            <Label className="text-xs text-muted-foreground">Status</Label>
                            <div className="mt-1">
                                {contact.is_replied ? (
                                    <Badge variant="default">Replied</Badge>
                                ) : (
                                    <Badge variant="secondary">Pending</Badge>
                                )}
                            </div>
                        </div>
                        {contact.is_replied && contact.replied_at && (
                            <div>
                                <Label className="text-xs text-muted-foreground">Replied At</Label>
                                <p className="text-sm font-medium">
                                    {new Date(contact.replied_at).toLocaleString()}
                                    {contact.replied_at_human ? (
                                        <span className="text-xs text-muted-foreground ml-2">
                                            ({contact.replied_at_human})
                                        </span>
                                    ) : null}
                                </p>
                                {contact.replied_by && (
                                    <p className="text-xs text-muted-foreground mt-1">
                                        by {contact.replied_by.name}
                                    </p>
                                )}
                            </div>
                        )}
                        <div>
                            <Label className="text-xs text-muted-foreground">Submitted</Label>
                            <p className="text-sm font-medium">
                                {new Date(contact.created_at).toLocaleString()}
                                {contact.created_at_human ? (
                                    <span className="text-xs text-muted-foreground ml-2">
                                        ({contact.created_at_human})
                                    </span>
                                ) : null}
                            </p>
                        </div>
                    </div>

                    {/* Message */}
                    <div>
                        <Label className="text-xs text-muted-foreground">Message</Label>
                        <div className="mt-2 p-3 bg-muted/50 rounded-md">
                            <p className="text-sm whitespace-pre-wrap">{contact.message}</p>
                        </div>
                    </div>

                    {/* Reply Section */}
                    {contact.is_replied && contact.reply_message && (
                        <div>
                            <Label className="text-xs text-muted-foreground">Previous Reply</Label>
                            <div className="mt-2 p-3 bg-blue-50 dark:bg-blue-950/20 rounded-md border border-blue-200 dark:border-blue-800">
                                <p className="text-sm whitespace-pre-wrap">{contact.reply_message}</p>
                            </div>
                        </div>
                    )}

                    {/* Reply Form */}
                    {!contact.is_replied && (
                        <div>
                            <Label htmlFor="reply_message">Reply Message</Label>
                            <Textarea
                                id="reply_message"
                                value={replyMessage}
                                onChange={(e) => setReplyMessage(e.target.value)}
                                placeholder="Enter your reply message here..."
                                className="mt-2 min-h-[150px]"
                                disabled={sending}
                            />
                            <p className="text-xs text-muted-foreground mt-1">
                                This message will be sent via email to {contact.email}
                            </p>
                        </div>
                    )}
                </div>

                <DialogFooter className="gap-2 sm:gap-0">
                    <DialogClose asChild>
                        <Button type="button" variant="outline" disabled={sending}>
                            {contact.is_replied ? 'Close' : 'Cancel'}
                        </Button>
                    </DialogClose>
                    {!contact.is_replied && (
                        <Button 
                            type="button" 
                            onClick={handleReply}
                            disabled={sending || !replyMessage.trim()}
                        >
                            {sending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                            <Mail className="mr-2 h-4 w-4" />
                            Send Reply
                        </Button>
                    )}
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}

